
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftMULTDIVrightPOWDIV LPAREN MINUS MULT NUM PLUS POW RPARENexpr : expr PLUS exprexpr : expr MINUS exprexpr : expr MULT exprexpr : expr DIV exprexpr : expr POW exprexpr : NUM\n        | expr : LPAREN expr RPAREN'
    
_lr_action_items = {'NUM':([0,3,4,5,6,7,8,],[2,2,2,2,2,2,2,]),'PLUS':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,],[-7,4,-6,-7,-7,-7,-7,-7,-7,4,-1,-2,-3,-4,-5,-8,]),'MINUS':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,],[-7,5,-6,-7,-7,-7,-7,-7,-7,5,-1,-2,-3,-4,-5,-8,]),'MULT':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,],[-7,6,-6,-7,-7,-7,-7,-7,-7,6,6,6,-3,-4,-5,-8,]),'DIV':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,],[-7,7,-6,-7,-7,-7,-7,-7,-7,7,7,7,-3,-4,-5,-8,]),'POW':([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,],[-7,8,-6,-7,-7,-7,-7,-7,-7,8,8,8,8,8,8,-8,]),'$end':([0,1,2,4,5,6,7,8,10,11,12,13,14,15,],[-7,0,-6,-7,-7,-7,-7,-7,-1,-2,-3,-4,-5,-8,]),'LPAREN':([0,3,4,5,6,7,8,],[3,3,3,3,3,3,3,]),'RPAREN':([2,3,4,5,6,7,8,9,10,11,12,13,14,15,],[-6,-7,-7,-7,-7,-7,-7,15,-1,-2,-3,-4,-5,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expr':([0,3,4,5,6,7,8,],[1,9,10,11,12,13,14,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expr","S'",1,None,None,None),
  ('expr -> expr PLUS expr','expr',3,'p_expr_plus','parse.py',17),
  ('expr -> expr MINUS expr','expr',3,'p_expr_minus','parse.py',21),
  ('expr -> expr MULT expr','expr',3,'p_expr_mult','parse.py',25),
  ('expr -> expr DIV expr','expr',3,'p_expr_div','parse.py',29),
  ('expr -> expr POW expr','expr',3,'p_expr_pow','parse.py',33),
  ('expr -> NUM','expr',1,'p_expr_num','parse.py',37),
  ('expr -> <empty>','expr',0,'p_expr_num','parse.py',38),
  ('expr -> LPAREN expr RPAREN','expr',3,'p_expr_br','parse.py',42),
]
