
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'LPR LPS RPR RPSexpr : LPR expr RPR expr\n            | LPS expr RPS expr\n            | '
    
_lr_action_items = {'LPR':([0,2,3,6,7,],[2,2,2,2,2,]),'LPS':([0,2,3,6,7,],[3,3,3,3,3,]),'$end':([0,1,6,7,8,9,],[-3,0,-3,-3,-1,-2,]),'RPR':([2,4,6,7,8,9,],[-3,6,-3,-3,-1,-2,]),'RPS':([3,5,6,7,8,9,],[-3,7,-3,-3,-1,-2,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expr':([0,2,3,6,7,],[1,4,5,8,9,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expr","S'",1,None,None,None),
  ('expr -> LPR expr RPR expr','expr',4,'p_expr','parse.py',12),
  ('expr -> LPS expr RPS expr','expr',4,'p_expr','parse.py',13),
  ('expr -> <empty>','expr',0,'p_expr','parse.py',14),
]
