
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'LPR LPS RPR RPS S : \n          | E S\n          | A B E : X Y\n          | O PA : C S B : D S X : O S O : LPS Y : E P P : RPSC : LPR D : RPR'
    
_lr_action_items = {'$end':([0,1,2,9,10,11,12,13,15,17,19,20,],[-1,0,-1,-2,-3,-1,-13,-4,-5,-11,-7,-10,]),'LPS':([0,2,4,5,6,7,8,9,10,11,12,13,15,16,17,19,20,],[7,7,7,7,7,-9,-12,-2,-3,7,-13,-4,-5,-8,-11,-7,-10,]),'LPR':([0,2,5,6,7,8,11,12,13,15,17,20,],[8,8,8,8,-9,-12,8,-13,-4,-5,-11,-10,]),'RPR':([2,3,6,8,9,10,11,12,13,15,17,18,19,20,],[-1,12,-1,-12,-2,-3,-1,-13,-4,-5,-11,-6,-7,-10,]),'RPS':([5,7,13,14,15,17,20,],[17,-9,-4,17,-5,-11,-10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'S':([0,2,5,6,11,],[1,9,16,18,19,]),'E':([0,2,4,5,6,11,],[2,2,14,2,2,2,]),'A':([0,2,5,6,11,],[3,3,3,3,3,]),'X':([0,2,4,5,6,11,],[4,4,4,4,4,4,]),'O':([0,2,4,5,6,11,],[5,5,5,5,5,5,]),'C':([0,2,5,6,11,],[6,6,6,6,6,]),'B':([3,],[10,]),'D':([3,],[11,]),'Y':([4,],[13,]),'P':([5,14,],[15,20,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> S","S'",1,None,None,None),
  ('S -> <empty>','S',0,'p_s','parse.py',12),
  ('S -> E S','S',2,'p_s','parse.py',13),
  ('S -> A B','S',2,'p_s','parse.py',14),
  ('E -> X Y','E',2,'p_e','parse.py',16),
  ('E -> O P','E',2,'p_e','parse.py',17),
  ('A -> C S','A',2,'p_a','parse.py',20),
  ('B -> D S','B',2,'p_b','parse.py',23),
  ('X -> O S','X',2,'p_x','parse.py',26),
  ('O -> LPS','O',1,'p_o','parse.py',29),
  ('Y -> E P','Y',2,'p_y','parse.py',32),
  ('P -> RPS','P',1,'p_p','parse.py',34),
  ('C -> LPR','C',1,'p_c','parse.py',37),
  ('D -> RPR','D',1,'p_d','parse.py',40),
]
